CREATE TABLE public.project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

DO $$
BEGIN
    PERFORM public.add_audit_columns('public', 'project');
END $$;

ALTER TABLE public.project ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable select for authenticated users" 
ON public.project 
FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Enable insert for Project Managers" 
ON public.project 
FOR INSERT 
TO authenticated 
WITH CHECK ((SELECT public.has_role('Project Manager')));

CREATE POLICY "Enable update for project owners" 
ON public.project 
FOR UPDATE 
TO authenticated 
USING ((created_by = (SELECT auth.uid())));

CREATE POLICY "Enable delete for project owners" 
ON public.project 
FOR DELETE 
TO authenticated 
USING ((created_by = (SELECT auth.uid())));
