CREATE TABLE public.task_priority (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

DO $$
BEGIN
    PERFORM public.add_audit_columns('public', 'task_priority');
END $$;

ALTER TABLE public.task_priority ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable select for authenticated users" ON public.task_priority FOR SELECT TO authenticated USING (TRUE);
